### ISSUE TITLE
Failed to load document: assets/content/docs/guides/intro.html. Error: Not Found

### ISSUE THREAD

**Issue by ziqiangai** [docgeni/docgeni-template#7]
![image](https://user-images.githubusercontent.com/18455767/143375353-eec54578-1950-4414-a98a-e253b7f5cc86.png)

仅仅是使用的模板没有做任何更改。

**Comment by why520crazy** [comment]
What operating system do you use?

**Comment by Exclamation-mark** [comment]
> 

win10

**Comment by why520crazy** [comment]
@Exclamation-mark It may be a compatibility issue with windows, we check it.

**Comment by Exclamation-mark** [comment]
> @Exclamation-mark It may be a compatibility issue with windows, we check it.

Come On.Make angular stronger!!!

**Comment by why520crazy** [comment]
Fixed, yan can try it, thank your feedback!
